import { useState, useEffect, useRef } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import { ChevronLeft, Printer, Download } from 'lucide-react'
import jsPDF from 'jspdf'

export default function ShippingLabelPage() {
    const { orderId } = useParams<{ orderId: string }>()
    const navigate = useNavigate()
    const [order, setOrder] = useState<any>(null)
    const [loading, setLoading] = useState(true)
    const labelRef = useRef<HTMLDivElement>(null)

    useEffect(() => {
        fetch(`/api/orders/${orderId}`, { credentials: 'include' })
            .then(r => r.json())
            .then(d => { setOrder(d); setLoading(false) })
    }, [orderId])

    const handlePrint = () => {
        window.print()
    }

    const handleDownloadPDF = () => {
        if (!order) return
        const doc = new jsPDF({ unit: 'mm', format: [100, 150] })

        // Header
        doc.setFillColor(123, 45, 139) // purple
        doc.rect(0, 0, 100, 25, 'F')
        doc.setTextColor(255, 255, 255)
        doc.setFontSize(14)
        doc.setFont('helvetica', 'bold')
        doc.text('SHIPPING LABEL', 50, 11, { align: 'center' })
        doc.setFontSize(8)
        doc.text('SellerDesk — Meesho Order', 50, 18, { align: 'center' })

        // Barcode-like decoration
        doc.setFillColor(255, 255, 255)
        doc.rect(5, 27, 90, 0.5, 'F')

        // Order details
        doc.setTextColor(30, 30, 30)
        doc.setFontSize(9)
        doc.setFont('helvetica', 'bold')
        doc.text('ORDER DETAILS', 8, 38)

        doc.setFillColor(245, 240, 248)
        doc.rect(5, 40, 90, 85, 'F')

        const fields = [
            ['Order ID:', order.orderId],
            ['Product:', order.productName],
            ['SKU:', order.sku],
            ['Quantity:', String(order.quantity)],
            ['Customer State:', order.customerState],
            ['Status:', order.status],
            ['Sale Price:', `Rs. ${order.salePrice}`],
            ['Date:', new Date(order.createdAt).toLocaleDateString('en-IN')],
        ]

        doc.setFont('helvetica', 'normal')
        fields.forEach(([label, val], i) => {
            const y = 48 + i * 10
            doc.setFont('helvetica', 'bold')
            doc.setTextColor(100, 50, 120)
            doc.text(label, 10, y)
            doc.setFont('helvetica', 'normal')
            doc.setTextColor(30, 30, 30)
            doc.text(String(val).substring(0, 28), 45, y)
        })

        // Footer
        doc.setFillColor(123, 45, 139)
        doc.rect(0, 135, 100, 15, 'F')
        doc.setTextColor(255, 255, 255)
        doc.setFontSize(7)
        doc.text('Generated by SellerDesk — Meesho Seller Management', 50, 143, { align: 'center' })

        doc.save(`shipping-label-${order.orderId}.pdf`)
    }

    if (loading) {
        return (
            <div className="min-h-screen flex items-center justify-center">
                <div className="w-8 h-8 border-2 border-purple-700 border-t-transparent rounded-full animate-spin" />
            </div>
        )
    }

    if (!order) {
        return (
            <div className="min-h-screen flex items-center justify-center flex-col gap-4">
                <p className="text-gray-500">Order not found</p>
                <button onClick={() => navigate('/orders')} className="btn-primary">Back to Orders</button>
            </div>
        )
    }

    return (
        <div className="page-enter">
            <div className="bg-gradient-to-br from-purple-800 to-purple-600 text-white px-4 pt-14 pb-6 print:hidden">
                <button onClick={() => navigate(-1)} className="flex items-center gap-1 text-purple-200 text-sm mb-4">
                    <ChevronLeft size={16} /> Back
                </button>
                <h1 className="text-xl font-extrabold">Shipping Label</h1>
                <p className="text-purple-200 text-sm">{order.orderId}</p>
            </div>

            <div className="px-4 py-4">
                {/* Label Preview */}
                <div ref={labelRef} className="bg-white border-2 border-gray-200 rounded-2xl overflow-hidden shadow-lg max-w-sm mx-auto print:border-black print:rounded-none print:shadow-none" id="shipping-label">
                    {/* Header */}
                    <div className="bg-purple-700 text-white px-6 py-4 text-center">
                        <h2 className="text-lg font-extrabold tracking-wide">SHIPPING LABEL</h2>
                        <p className="text-purple-200 text-xs mt-0.5">SellerDesk — Meesho Order</p>
                    </div>

                    {/* Separator */}
                    <div className="flex gap-1 px-4 py-2">
                        {Array(12).fill(0).map((_, i) => (
                            <div key={i} className="flex-1 h-1.5 bg-purple-700 rounded-full" />
                        ))}
                    </div>

                    {/* Details */}
                    <div className="px-6 py-4 space-y-3">
                        {[
                            { label: 'Order ID', val: order.orderId, bold: true },
                            { label: 'Product', val: order.productName },
                            { label: 'SKU', val: order.sku },
                            { label: 'Quantity', val: order.quantity },
                            { label: 'Customer State', val: order.customerState },
                            { label: 'Status', val: order.status },
                            { label: 'Sale Price', val: `₹${order.salePrice}` },
                            { label: 'Date', val: new Date(order.createdAt).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) },
                        ].map(({ label, val, bold }) => (
                            <div key={label} className="flex items-start justify-between gap-4">
                                <span className="text-xs font-bold text-gray-500 uppercase tracking-wide flex-none w-28">{label}</span>
                                <span className={`text-sm text-right ${bold ? 'font-extrabold text-purple-700 text-base' : 'font-semibold text-gray-800'}`}>{String(val)}</span>
                            </div>
                        ))}
                    </div>

                    {/* Footer */}
                    <div className="bg-purple-700 text-white text-center py-2">
                        <p className="text-xs text-purple-200">Generated by SellerDesk</p>
                    </div>
                </div>

                {/* Action buttons */}
                <div className="flex gap-3 mt-6 print:hidden">
                    <button onClick={handlePrint} className="flex-1 flex items-center justify-center gap-2 btn-secondary py-3">
                        <Printer size={18} /> Print
                    </button>
                    <button onClick={handleDownloadPDF} className="flex-1 flex items-center justify-center gap-2 btn-primary py-3">
                        <Download size={18} /> Download PDF
                    </button>
                </div>
            </div>
        </div>
    )
}
